// examples/letter-address-vuejs3/src/App.vue
<!-- SPDX-License-Identifier: MIT -->
<script setup lang=ts>
import ControlBar from '@/components/ControlBar.vue';
</script>

<script lang=ts>
export default {
  mounted() {
    const config_js = document.createElement("script");
    config_js.src = "./config.js";
    document.body.appendChild(config_js);  // May fail. config.js is optional.
    const pre_soffice_js = document.createElement("script");
    pre_soffice_js.type = "module";
    pre_soffice_js.src = "./pre_soffice.js";    pre_soffice_js.onload = function () {
      console.log('pre_soffice.js loaded');
      // Try to connect the Vue component if it's already mounted
      if (window.vueControlBarComponent && window.jsPassCtrlBar) {
        console.log('Connecting Vue component to pre_soffice.js');
        window.jsPassCtrlBar(window.vueControlBarComponent);
      }
    }
    document.body.appendChild(pre_soffice_js);
  },
};
</script>

<template>
  <div id="app">
    <div class="container-fluid p-0" style="width:1150px; margin:auto;">
      <div class="row">
        <div class="col mt-3 mb-2">
          <h1>ZetaJS: Letter Address Vue.js-3</h1>
        </div>
      </div>
      <div class="row">
        <ul class="nav nav-tabs" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active" id="btnLetter" onclick="btnSwitchTab('letter')" type="button" role="tab"
              aria-controls="home-tab-pane" aria-selected="true" disabled>Editor</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link" id="btnTable" onclick="btnSwitchTab('table')" type="button" role="tab"
              aria-controls="profile-tab-pane" aria-selected="false" disabled>Addresses</button>
          </li>
        </ul>
        <div class="tab-content p-1" id="tabContent">
          <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="btnLetter"
            tabindex="0">
            <div class="row">
              <!-- The ControlBar may extend horizontally if the selected font family has a long name. -->
              <ControlBar id="controlbar" class="mt-1 mb-1" />
              <div id="canvasCell" class="col-lg-9">
                <div class="canvas-container" onselectstart="event.preventDefault()">
                  <div id="loadingInfo" class="loading-info">
                    <div class="spinner"></div><br>
                    <h2>ZetaOffice is loading...</h2>
                  </div>
                  <canvas id="qtcanvas" contenteditable="true" oncontextmenu="event.preventDefault()"
                    onkeydown="event.preventDefault()" style="width:870px; height:500px; visibility:hidden;"
                    class="qt-canvas">
                    <!-- Qt requires the canvas to have the ID "qtcanvas". -->
                    <!-- The canvas *must not* have any border or padding, or mouse coords will be wrong. -->
                    <!-- An outline is fine though. -->
                  </canvas>
                </div>
              </div>
              <div id="controlCell" class="col-lg-3">
                <h4>Document</h4>
                <label class="btn btn-light btn-sm disabled" id="lblUpload">
                  Upload new file
                  <input accept=".odt" class="file-input" type="file" id="btnUpload" onchange="btnUploadFunc()" disabled>
                </label>
                <button class="btn btn-light btn-sm ms-2" id="btnReload" onclick="btnReloadFunc()" disabled>
                  Reload file</button>
                <div id="addrNameCell">
                  <div class="d-flex justify-content-between">
                    <h4 class="mt-3">Recipient</h4>
                    <button class="btn btn-primary btn-sm mb-2 mt-3" id="btnInsert"
                      onclick="btnInsertFunc()" disabled>Insert Address</button>
                  </div>
                  <!-- size: Somehow needs about 3 rows more space when deployed on the website. -->
                  <select class="form-select" id="addrName" size="13" autofocus disabled></select>
                </div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</template>


<style>
.spinner {
  border: 16px solid #1F2937;
  /* ZetaOffice brand color */
  border-top: 16px solid #059669;
  /* ZetaOffice brand color */
  border-radius: 50%;
  width: 120px;
  height: 120px;
  position: relative;
  left: 60px;
  /* adjust to center */
  animation: spin 2s linear 30;
  /* 60 seconds */
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}

/* Disable dark mode. ControlBar doesn't work well with it. */
body {
  background-color: var(--background-color);
  color: var(--text-color);
}

.container {
  padding: 0;
}

.file-input {
  display: none;
}

.canvas-container {
  position: relative;
}

.loading-info {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.qt-canvas {
  border: 0px none;
  padding: 0;
  /*outline: 1px solid #cccccc;*/
}

#tabContent {
  border: 1px solid var(--bs-border-color);
  ;
  border-top: none;
}
</style>

// examples/letter-address-react/src/App.tsx
import React, { useEffect, useRef } from 'react'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { ControlBar } from '@/components/ControlBar'
import './index.css'

declare global {
  interface Window {
    reactControlBarComponent: any;
    jsPassCtrlBar: (component: any) => void;
    btnSwitchTab: (tab: string) => void;
    btnUploadFunc: () => void;
    btnReloadFunc: () => void;
    btnInsertFunc: () => void;
  }
}

const App: React.FC = () => {
  const controlBarRef = useRef<any>(null);

  useEffect(() => {
    // Store reference to this component globally so pre_soffice.js can access it
    window.reactControlBarComponent = controlBarRef.current;

    // Load config.js (optional)
    const configScript = document.createElement('script');
    configScript.src = './config.js';
    document.body.appendChild(configScript);

    // Load pre_soffice.js
    const preSofficeScript = document.createElement('script');
    preSofficeScript.type = 'module';
    preSofficeScript.src = './pre_soffice.js';
    preSofficeScript.onload = () => {
      console.log('pre_soffice.js loaded');
      // Try to connect the React component if it's available
      if (window.reactControlBarComponent && window.jsPassCtrlBar) {
        console.log('Connecting React component to pre_soffice.js');
        window.jsPassCtrlBar(window.reactControlBarComponent);
      }
    };
    document.body.appendChild(preSofficeScript);

    return () => {
      // Cleanup scripts on unmount
      document.body.removeChild(configScript);
      document.body.removeChild(preSofficeScript);
    };
  }, []);

  return (
    <div id="app" className="min-h-screen bg-background">
      <div className="container mx-auto max-w-7xl p-0">
        <div className="mt-6 mb-4">
          <h1 className="text-3xl font-bold">ZetaJS: Letter Address React</h1>
        </div>
        
        <Tabs defaultValue="editor" className="w-full">
          <TabsList className="grid w-full grid-cols-2 max-w-md">
            <TabsTrigger value="editor" id="btnLetter">
              Editor
            </TabsTrigger>
            <TabsTrigger value="addresses" id="btnTable">
              Addresses  
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="editor" className="mt-4 space-y-4 border border-border rounded-lg p-4">
            <ControlBar ref={controlBarRef} id="controlbar" />
            
            <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
              <div id="canvasCell" className="lg:col-span-3">
                <div className="canvas-container relative">
                  <div id="loadingInfo" className="loading-info">
                    <div className="spinner"></div>
                    <h2 className="text-2xl font-semibold">ZetaOffice is loading...</h2>
                  </div>
                  <canvas
                    id="qtcanvas"
                    contentEditable="true"
                    onContextMenu={(e) => e.preventDefault()}
                    onKeyDown={(e) => e.preventDefault()}
                    style={{ width: '870px', height: '500px', visibility: 'hidden' }}
                    className="qt-canvas"
                  />
                </div>
              </div>
              
              <div id="controlCell" className="lg:col-span-1 space-y-4">
                <div>
                  <h4 className="text-lg font-semibold mb-2">Document</h4>
                  <div className="space-y-2">
                    <label className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80 h-8 px-3 cursor-pointer disabled:opacity-50 disabled:pointer-events-none" id="lblUpload">
                      Upload new file
                      <input
                        accept=".odt"
                        className="file-input"
                        type="file"
                        id="btnUpload"
                        onChange={() => window.btnUploadFunc?.()}
                        disabled
                      />
                    </label>
                    <button
                      className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80 h-8 px-3 ml-2 disabled:opacity-50 disabled:pointer-events-none"
                      id="btnReload"
                      onClick={() => window.btnReloadFunc?.()}
                      disabled
                    >
                      Reload file
                    </button>
                  </div>
                </div>
                
                <div id="addrNameCell">
                  <div className="flex justify-between items-center mb-2">
                    <h4 className="text-lg font-semibold">Recipient</h4>
                    <button
                      className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors bg-primary text-primary-foreground shadow hover:bg-primary/90 h-8 px-3 disabled:opacity-50 disabled:pointer-events-none"
                      id="btnInsert"
                      onClick={() => window.btnInsertFunc?.()}
                      disabled
                    >
                      Insert Address
                    </button>
                  </div>
                  <select
                    className="flex h-auto w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                    id="addrName"
                    size={13}
                    autoFocus
                    disabled
                  />
                </div>
              </div>
            </div>
          </TabsContent>
          
          <TabsContent value="addresses" className="mt-4 border border-border rounded-lg p-4">
            <div id="canvasCell" className="w-full">
              <div className="canvas-container relative">
                <div id="loadingInfo" className="loading-info">
                  <div className="spinner"></div>
                  <h2 className="text-2xl font-semibold">ZetaOffice is loading...</h2>
                </div>
                <canvas
                  id="qtcanvas"
                  contentEditable="true"
                  onContextMenu={(e) => e.preventDefault()}
                  onKeyDown={(e) => e.preventDefault()}
                  style={{ width: '870px', height: '546px', visibility: 'hidden' }}
                  className="qt-canvas"
                />
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  )
}

export default App
